server:
  port: 8080
spring:
  application:
    name: "franchising-project"
  devtools:
    add-properties: false
  flyway:
    enabled: true
    locations: classpath:db/migration
  r2dbc:
    url:  ${URL_DATABASE}
    username: ${USER_DATABASE}
    password: ${PASS_DATABASE}
    driverClassName: ${DRIVER_DATABASE:com.mysql.cj.jdbc.Driver}

management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
