version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: franchising-db
    restart: always
    environment:
      MYSQL_DATABASE: franchising_db
      MYSQL_ROOT_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  api:
    build:
      context: ./../
      dockerfile: deployment/Dockerfile
    container_name: franchising-api
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      URL_DATABASE: r2dbc:mysql://franchising-db:3306/franchising_db
      USER_DATABASE: root
      PASS_DATABASE: admin
      DRIVER_DATABASE: com.mysql.cj.jdbc.Driver
    restart: always

volumes:
    db_data:
        driver: local